### ISSUE TITLE
RefCall variants

### ISSUE THREAD

**Issue by sq101** [HKU-BAL/ClairS-TO#11]
Hi there! We are testing clairS-TO with the `--print_ref_calls` option. My question is: what does the RefCall flag mean? Could you further elaborate on it? 

I am aware that in other software it can mean that the variant was proposed as mutation but later is rejected by the variant caller; however, I would appreciate if you can provide further information on what it means in ClairS-TO.

Thank you very much and thank you as well for your tool!
Regards!

**Comment by JasonCLEI** [comment]
Hi @sq101 as for your questions:

a) ClairS-TO first extracts variant candidates through a simple heuristic approach, and then our neural networks classify whether these variant candidates are real variants or not. Those candidates rejected by our neural networks as not real variants are flagged as `RefCall`.

b) RefCalls are not LowQual variants. LowQual variants are those variants that have been classified as real variants by our neural networks but have not passed subsequent quality control filters. But RefCalls are those rejected by our neural networks and classified as reference calls.

c) RefCall flags allow us to obtain a full record of every variant candidate that ClairS-TO was asked to classify. RefCalls are more likely to be true negatives (true reference calls) and an indication of sequencing artifacts as you said. In addition, it allows users to design different filtering strategies in the event they want to increase recall but inevitably increasing a large number of false positives.

I hope these explanations can give you some insights. Thanks a lot for your interest on ClairS-TO.

Lei
