### ISSUE TITLE
Different output

### ISSUE THREAD

**Issue by pcr876** [HKU-BAL/ClairS-TO#13]
Hi,

First of all thank you for ClairS-TO. 
I have been trying to use it with bed file option.
I get different output for the same sample if I re-run it.
In some output, it skips certain positions of a chromosome. It shows in the tmp file if I check individual chromosome vcf file. But some positions or entire chromosome get missed out in a merged output vcf. Also does not show phasing in a final vcf.

Thank you in advance.

Shreya

**Comment by aquaskyline** [comment]
can you send us the complete log file.

**Comment by pcr876** [comment]
Could you please tell me which log file should I send? It creates many?
