### ISSUE TITLE
make read start/end filter available in parameters

### ISSUE THREAD

**Issue by maxstengl** [HKU-BAL/ClairS-TO#17]
Hi,
we want to analyze somatic mutations on ONT short reads (300-500bps).
You are filtering and removing variants that are close (100bp?, reported qual set to 0, filter: LowQual;ReadStartEnd) 
to start and end of a read. 
Is there a way to change this filtering (via parameters?) or would you generally advise no to use clairs-to for variant calling of such sort reads (we find the quality at the start and end of our reads sufficient for this purpose).
Thank you.

**Comment by JasonCLEI** [comment]
Hi, @maxstengl,

Thanks a lot for your interest. We recommend using read start and end filtering to obtain reliable results. However, regarding as your question, we have added an option `--disable_read_start_end_filtering` to disable read start and end filtering, and released a new Docker image of ClairS-TO. You could rerun the program with your ONT short reads with the latest image of ClairS-TO by adding an option `--disable_read_start_end_filtering True` and check the results.

Lei
