### ISSUE TITLE
bcftools doesn't like tag name '1kGPoN'

### ISSUE THREAD

**Issue by ymcki** [HKU-BAL/ClairS-TO#3]
I am getting "[W::bcf_hrec_check] Invalid tag name: "1kGPoN"" error when processing the vcf generated by ClairS-TO pipeline.

My understanding is that bcftools doesn't like any tag that starts with a number. 

Can you change the tag name to PoN instead in shared/vcf.py line 24 and src/nonsomatic_tagging.py line 294?

Thanks a lot in advance.

**Comment by aquaskyline** [comment]
We will change all PoN tags in the next version. v0.0.2 will be released by this week.

**Comment by ymcki** [comment]
Thanks for your quick reply. Looking forward to trying 0.0.2. 

Does 0.0.2 support short indels? It seems to me 0.0.1 doesn't support.

**Comment by aquaskyline** [comment]
No, still working on that.

**Comment by ymcki** [comment]
Thanks for your reply. I find that 0.0.2 fixed 1kGPoN problem, so I think this can be closed.
