### ISSUE TITLE
Get a large number of variants from ClairS-TO

### ISSUE THREAD

**Issue by ywzhang071394** [HKU-BAL/ClairS-TO#7]
Hi, I am using Clairs-TO to call somatic small variant from PacBio Revio tumor data. As a result, ClairS-TO detected ~28000 variants, which is much larger than I expected. I am not sure whether there are many false positive and thus post this issue to enquire if it's normal condition when using ClairS-TO.

Thanks!

**Comment by aquaskyline** [comment]
Quite a number of variants in your 28k calls are germline, do you have any PoNs for filtering the calls?

**Comment by ywzhang071394** [comment]
We used the default PoNs, which is embedded in the ClairS-TO package.

**Comment by aquaskyline** [comment]
You might want to find or construct a PoN that is specific to your cancer type or population to further reduce the number of variants.
