### ISSUE TITLE
F1 scores and high coverage datasets

### ISSUE THREAD

**Issue by sq101** [HKU-BAL/ClairS-TO#9]
Hi there!! We're currently testing ClairS-To using ONT DNA reads and a variant truth set to call SNPs. We have noticed; however, that the F1 score decreases relevently whenever the coverage is above 1000x (e.g. F1 of 0.90 if cov. 1000x, F1 of 0.5 when using higher coverage).

Therefore, I wanted to kindly ask: could there be a reason for this behaviour?

Thank you very much for any reply in advance and thank you very much for ClairS-TO
Cheers!

**Comment by aquaskyline** [comment]
The model wasn't trained with that much excessive coverage. We suggest downsampling to below 1000x.
